/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoestructura.ventanas;

import java.awt.BorderLayout;
import java.awt.Dimension;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;
import org.graphstream.ui.view.Viewer;
import proyectoestructura.Grafo;
import proyectoestructura.Vertice;

/**
 *
 * @author sebas
 */
public class mostrargrafo extends javax.swing.JFrame {
    static Grafo grafo;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mostrargrafo.class.getName());

    /**
     * Creates new form mostrargrafo
     */
    public mostrargrafo(Grafo nuevo) {
        initComponents();
        this.grafo = nuevo;
        this.setVisible(true);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); 
        this.setTitle("Analizador de Red Social (Grafos)");
        this.setPreferredSize(new Dimension(800, 600)); 
        this.pack();
        this.setLocationRelativeTo(null);
        dibujarGrafo();
                
    }
    private void dibujarGrafo() {

        if (grafo == null) {
            return;
        }

        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("RedSocial");
        String stylesheet = "graph {" + "fill-color:#222222;" + "}" + "node{" + "text-size: 25px;" + "text-color:white;" + "}";
        graph.setAttribute("ui.stylesheet", stylesheet);

        Vertice[] vertices = grafo.getVertices();
        for (Vertice v : vertices) {
            graph.addNode(v.proteina).setAttribute("ui.label", v.proteina);
        }

        int edgeId = 0;
        for (Vertice v : vertices) {
            String[] nombresAdyacentes = v.aristas.getNombres();
            for (String adyacente : nombresAdyacentes) {
                if (graph.getNode(adyacente) != null) {
                    graph.addEdge(String.valueOf(edgeId++), v.proteina, adyacente, true);
                }
            }
        }

        Viewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);

        panel.setLayout(new BorderLayout());
        panel.add(viewPanel, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mostrar Grafo");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jButton1.setText("Mostrar Grafo");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jButton2.setText("Atras");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Menuinicial m = new Menuinicial (grafo);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mostrargrafo(grafo).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
